### ISSUE TITLE
How to set other parameters?

### ISSUE THREAD

**Issue by tomwwagstaff-product** [MicrosoftDocs/azure-reference-other#72] opened 2019-04-08 12:31 UTC
I want to specify an offset term amongst the predictors - I can't see a way to do this either in the Poisson regression module or in the "train model"  module - I can select an output variable and it looks like all the rest are automatically added as normal predictor variables. Is there a way to choose an offset term (and transform it if necessary)?

Also, is there a way to specify the link function? What's the default link function - is it a log link?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f49234ca-1e4e-945e-8e0f-3168b822d153
* Version Independent ID: eb150cf9-2dbd-70a1-c70c-990d2ce2f256
* Content: [Poisson Regression - Azure Machine Learning Studio](https://docs.microsoft.com/en-us/azure/machine-learning/studio-module-reference/poisson-regression)
* Content Source: [studio-module-reference/poisson-regression.md](https://github.com/MicrosoftDocs/azure-reference-other/blob/master/studio-module-reference/poisson-regression.md)
* Service: **machine-learning**
* Sub-service: **studio**
* GitHub Login: @xiaoharper
* Microsoft Alias: **amlstudiodocs**

**Comment by tomwwagstaff-product** [comment] 2019-04-08 13:57
It's OK, I think the answer to this is use "Create R Model" if you want to specify these parameters, right?

**Comment by JasonWHowell** [comment] 2019-04-08 22:25
@xiaoharper @j-martens FYI

**Comment by j-martens** [comment] 2019-04-09 01:05
Hi Tom, is this a duplicate of #73?

**Comment by tomwwagstaff-product** [comment] 2019-04-09 10:07
Hi @j-martens,

No, in #73 I was asking how to retrain a model built using custom R code, in this one I was wondering if I could set these parameters without resorting to custom R code. I'm guessing the answer to that is no, but that's fine now I know how to do it with custom R code.

It would still be good to confirm the link function your native Poisson regression module uses. I'm guessing it's a log link?

**Comment by xiaoharper** [comment] 2019-04-11 06:31
@tomwwagstaff-product  You are right, there is no option to set offset term in the build-in Poisson regression module, using R/Python is the right choice.  And log link is probably used here (I can't say for sure given there is no description in the toolkit document used for the modules.)

**Comment by tomwwagstaff-product** [comment] 2019-04-11 10:01
Hello @xiaoharper,

Thanks very much for confirming this - sounds like it's best to stick with custom code if you want to be sure you know exactly what model you're estimating.

**Closed** 2019-04-11 10:01 UTC
