### ISSUE TITLE
'Bias' is being displayed as a feature with weight(coefficient value ) while visualizing the Model in Azure ML

### ISSUE THREAD

**Issue by getsrikar** [MicrosoftDocs/azure-reference-other#122] opened 2020-06-12 09:14 UTC
![Feature_Weights](https://user-images.githubusercontent.com/5341431/84486225-b80d5f00-acba-11ea-8a9c-e2554c8bbbcf.png)

Please find the above snapshot for reference. 'Bias' should never be displayed as an individual feature under the list of features with feature weights, as this doesn't make sense and confuses the audience to assume it as a potential/individual feature also impacting the model performance. Kindly correct this issue in your Azure ML Studio.

**Comment by j-martens** [comment] 2020-06-16 13:46
@getsrikar thanks for bringing this to our attention. We have submitted your information to the engineering team to research. We hope to get a reply soon.

**Comment by likebupt** [comment] 2020-08-05 07:09
@mamccrea   Thanks for your feedback. The "Bias" is by design shown in the Trained Model Studio (classic) is in only-maintenance mode now, which means there will be no new investment. We suggest the new [Designer ](https://docs.microsoft.com/en-us/azure/machine-learning/concept-designer)as an alternative for you to explore.

**Comment by j-martens** [comment] 2020-08-06 15:21
Thanks for your post. We will now proceed to close this thread. #please-close

**Closed by j-martens** 2020-08-06 15:21 UTC
